woowacourse-teams/2021-tyf

client/src/App.tsx, client/webpack.config.ts
=> [#31] PUBLIC_URL 환경변수 세팅

server/src/main/java/com/example/tyfserver/auth/config/OAuth2TypeDependencyInjector.java, server/src/main/java/com/example/tyfserver/auth/domain/Oauth2Type.java, server/src/main/java/com/example/tyfserver/auth/service/OAuth2Service.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/dto/SignUpRequest.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepository.java
=> [#41] 컴파일 에러 해결 - oauth2 jpa 테이블 명 수정

server/src/main/java/com/example/tyfserver/banner/service/BannerService.java, server/src/main/java/com/example/tyfserver/donation/controller/DonationController.java, server/src/main/java/com/example/tyfserver/donation/domain/Donation.java, server/src/main/java/com/example/tyfserver/donation/domain/Message.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationMessageRequest.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationResponse.java, server/src/main/java/com/example/tyfserver/donation/repository/DonationRepository.java, server/src/main/java/com/example/tyfserver/donation/service/DonationService.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepository.java, server/src/test/java/com/example/tyfserver/donation/DonationAcceptanceTest.java, server/src/test/java/com/example/tyfserver/donation/repository/DonationRepositoryTest.java
Close #58 
해당 api 수행했습니다.  
위 메서드는 secret이 false인 것만 들고오는 메서드인데, 저희 api에서는 사용하지 않고 있습니다. 처음에 착각하고 만들었는데 이후 변동사항 있을 수 있어서 그대로 내비뒀습니다.  
테스트 작성도 해놨습니다.
=> [#58] 후원 리스트 API 작성

client/public/netlify.toml, client/src/__test__/RegisterTermsPage.test.tsx, client/src/components/Register/RegisterAuthForm/RegisterAuthForm.styles.ts, client/src/components/Register/RegisterAuthForm/RegisterAuthForm.tsx, client/src/components/Register/RegisterTermsForm/RegisterTermsForm.tsx, client/src/constants/constant.ts, client/src/service/hooks/useRegister.tsx, client/src/service/hooks/useRegisterAuth.tsx, client/src/service/hooks/useRegisterTerms.tsx
[특이사항]
- 이용약관 페이지 미구현
- 외부인증 페이지 출력하지만, redirect는 되지 않음 (논의 필요)
=> [#57] 회원가입 약관동의, 외부인징 페이지 기능 구현

client/src/API.ts, client/src/App.tsx, client/src/components/@atom/Modal/Modal.tsx, client/src/components/Menu/Menu.stories.tsx, client/src/components/Menu/Menu.styles.ts, client/src/components/Menu/Menu.tsx, client/src/components/NavBar/NavBar.tsx, client/src/service/hooks/useLoginUserInfo.ts, client/src/service/hooks/useLogout.ts, client/src/service/request/auth.ts, client/src/service/request/creator.ts, client/src/service/share.ts, client/src/service/state/login.ts, client/src/utils/useModal.ts, client/src/utils/webShareAPI.ts
1. 로고버튼 메인페이지 라우팅
2. 햄버거 메뉴 로그인 분기 처리
3. 로그아웃 기능
4. 로그인한 유저, 라우팅 기능
5. 후원 URL 복사 기능 - Web Share API (Mobile only)
=> [#90] 네비게이션바 동작 기능 구현

server/src/main/resources/application-prod.yml, server/src/main/resources/application.yml
Closes #89 
- db server 외부에서 접근 가능하도록 수정
- - mysql 설정파일에서 외부 아이피 열어주기 (0.0.0.0으로 열어줌)
https://emong.tistory.com/235
- - mysql user host 설정에서 접근 가능한 produser 설정하기
- public key retrieval is not allowed 이슈 해결
https://joont92.github.io/java/java-mysql-%EC%97%B0%EB%8F%99%EC%8B%9C-%EC%98%A4%EB%A5%98/
=> [#89]DB 서버 테이블 업데이트

client/src/API.ts, client/src/components/Login/LoginForm.tsx, client/src/constants/storage.ts, client/src/service/hooks/useAccessToken.ts, client/src/service/hooks/useLoginEffect.ts, client/src/service/hooks/useLoginPersistenceType.ts, client/src/service/state/login.ts, client/src/types.ts, client/src/utils/storage.ts
- 새로고침시에도 유지, 창닫으면 삭제 -> 세션스토리지
- 창닫기시에도 유지, 토큰이 유효하지 않은 값이 될때까지 유지 -> 로컬스토리지
- 유효한 토큰이 스토리지에 존재한다면, 로그인이 유지된다.
- 사용자는 토큰 생명주기를 선택할 수 있다.
=> [#94] 유저는 로그인을 유지할 수 있다. 

server/src/main/java/com/example/tyfserver/auth/config/AuthenticationInterceptor.java, server/src/main/java/com/example/tyfserver/common/config/WebConfig.java
- cors addmapping /** 로 수정
- intercepter preflight 관련 수정
=> [#107] CORS 에러 수정

server/src/main/resources/application-oauth2-encrypted.yml, server/src/main/resources/application-oauth2.yml
- oauth2 property의 type을 대문자로 변경
- string type으로 enum값을 찾을 때, equalsIgnoreCase를 사용하면 되지 않을까?
=> [#109]Oauth2 Property의 type(소문자)과 queryParam으로 받는 type(대문자)이 다름 

server/build.gradle, server/src/main/java/com/example/tyfserver/common/config/GlobalExceptionHandler.java, server/src/main/resources/application-dev.yml, server/src/main/resources/application-prod.yml, server/src/main/resources/logback-spring.xml
Closes #115 
- logging 적용 
- error 발생 시 슬랙으로 알람 받기
- 미정의 에러 처리 추가
=> [#115]Logging 추가

client/src/App.tsx, client/src/components/@atom/Input/Input.tsx, client/src/components/Donation/DonationForm/DonationForm.stories.tsx, client/src/components/Donation/DonationForm/DonationForm.tsx, client/src/components/Donation/MessageForm/DonationMessageForm.stories.tsx, client/src/components/Donation/MessageForm/DonationMessageForm.tsx, client/src/constants/service.ts, client/src/index.tsx, client/src/pages/Donation/Donation/DonationPage.tsx, client/src/pages/Donation/Message/DonationMessagePage.tsx, client/src/pages/Donation/Success/DonationSuccessPage.styles.ts, client/src/pages/Donation/Success/DonationSuccessPage.tsx, client/src/service/hooks/useDonation.ts, client/src/service/hooks/useDonationForm.ts, client/src/service/hooks/useDonationMessage.ts, client/src/service/hooks/useDonationMessageForm.ts, client/src/service/request/creator.ts, client/src/service/request/donation.ts, client/src/service/state/donation.ts, client/src/types.ts, client/webpack.config.ts
- 존재하는 후원자인지 검증하는 기능은 인치가 만든거 쓰면 될듯
- 창 닫기 기능이 js로 하기 까다로운 것같아 ㅠㅠ 이거 좀 다시 봐야할듯
=> [#105] 후원 기능 구현

server/src/test/java/com/example/tyfserver/banner/repository/BannerRepositoryTest.java, server/src/test/java/com/example/tyfserver/donation/repository/DonationRepositoryTest.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java, server/src/test/java/com/example/tyfserver/member/repository/MemberRepositoryImplTest.java
=> [#113] /members/validate/token 컨트롤러 테스트 코드 추가 및 repositoryTest @Import 추가

server/src/main/resources/application-oauth2-encrypted.yml
- oauth2.0 회원가입 redirect url 변경
=> [#118] 회원가입 oauth2 RedirectURL 변경 

client/src/pages/Donation/Success/DonationSuccessPage.tsx, client/src/service/state/donation.ts
=> 후원 성공 페이지 새로고침시 비정상적 정보 표시되는 이슈

client/src/pages/Donation/Success/DonationSuccessPage.tsx, client/src/service/hooks/useRegister.tsx, client/src/service/request/register.ts
=> 회원가입 후 자동으로 로그인 되지 않는 현상

client/src/App.tsx, client/src/pages/Statistics/StatisticsPage.tsx, client/src/service/hooks/useLoginUserInfo.ts, client/src/service/hooks/useStatistics.ts, client/src/service/state/statistics.ts
=> 통계 페이지가 노출되지 않는 현상

server/src/main/resources/application-dev.yml
dev-server가 매번 배포될 때마다 데이터가 초기화되지 않도록 설정
=> [#137] dev-server의 데이터가 매번 배포될 때마다 초기화되지 않도록 변경

server/src/main/java/com/example/tyfserver/auth/config/AuthenticationPrincipalConfig.java
- https://thirsty-euler-f61b80.netlify.app/
=> [#141]클라이언트 배포 URL CORS 추가

client/src/components/Creator/DonationList/DonationList.tsx, client/src/service/hooks/useCreatorDonations.ts
fix: 후원목록 더보기 버튼이 목록이 5n개일때 보이는 문제 해결
=> release v1.0.1

client/src/components/Menu/Desktop/DesktopMenu.styles.ts, client/src/components/Menu/Menu.tsx, client/src/constants/storage.ts, client/src/service/hooks/useAccessToken.ts, client/src/service/hooks/useLoginEffect.ts, client/src/service/hooks/useLoginPersistenceType.ts, client/src/service/hooks/useRegister.ts, client/src/service/state/login.ts
- OAuth Provider가 tyf페이지로 다시 리다이렉션하는 흐름이어서 로그인유지여부의 상태유지 방식을 변경함
전역상태 -> 로컬스토리지
=> [#175] 로그인 유지하기 동작하지 않는 현상

server/src/main/java/com/example/tyfserver/donation/dto/DonationMessageRequest.java, server/src/main/java/com/example/tyfserver/member/dto/NicknameValidationRequest.java, server/src/main/java/com/example/tyfserver/member/dto/PageNameValidationRequest.java, server/src/main/java/com/example/tyfserver/member/dto/SignUpRequest.java
후원자 닉네임 유효성 변경점
길이 3~20 -> 길이  ~20
***
창작자 닉네임 유효성 변경점
길이 3~20  -> 길이 2~20
=> [#177] 닉네임 유효성 조건 및 @Pattern 어노테이션 정규표현식 수정

client/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.styles.ts, client/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.tsx, client/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.styles.ts, client/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.tsx, client/src/components/Register/AddressForm/RegisterAddressForm.styles.ts, client/src/components/Register/AddressForm/RegisterAddressForm.tsx, client/src/components/Register/NameForm/RegisterNameForm.styles.ts, client/src/components/Register/NameForm/RegisterNameForm.tsx, client/src/components/Register/TermsForm/RegisterTermsForm.styles.ts, client/src/components/Register/TermsForm/RegisterTermsForm.tsx, client/src/pages/Creator/CreatorPage.styles.ts, client/src/pages/Creator/CreatorPage.tsx, client/src/pages/Register/Address/RegisterAddressPage.styles.tsx, client/src/pages/Register/Name/RegisterNamePage.styles.ts, client/src/pages/Register/Terms/RegisterTermsPage.styles.ts
- creatorInfo 컴포넌트 데스크탑, 모바일 분리
- 회원가입 플로우 페이지들 반응형 웹 개선
=> [#180] 일부 반응형 웹 리팩토링

server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/dto/MemberResponse.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java
=> [#205]Member 응답 데이터에 bio 추가

client/src/components/Donation/AmountForm/DonationAmountForm.styles.ts, client/src/components/Donation/AmountForm/DonationAmountForm.tsx, client/src/components/Donation/DonatorForm/DonatorForm.tsx, client/src/components/Register/TermsForm/RegisterTermsForm.tsx, client/src/components/Setting/UserSettingForm/UserSettingForm.tsx, client/src/constants/donation.ts, client/src/service/hooks/useDonationAmountForm.ts, client/src/service/hooks/useSettingForm.ts, client/src/service/hooks/useURLBanner.ts, client/src/service/popup.ts, client/src/service/share.ts, client/src/service/state/login.ts, server/src/main/java/com/example/tyfserver/member/dto/CurationsResponse.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepositoryImpl.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java, server/src/test/java/com/example/tyfserver/member/repository/MemberRepositoryImplTest.java, server/src/test/java/com/example/tyfserver/member/service/MemberServiceTest.java
=> hotfix: 배포 후 검증 이슈 사항

client/src/service/hooks/useURLBanner.ts
s3파일 다 새로 익스포트해서 바꿔주고 
코드는 한줄변경함 ㅎ
=> [#217] 공유버튼 이미지 사이즈 균일화 + 확장자 svg로 변경 

client/src/constants/error.ts, client/src/service/hooks/useRegisterEffect.ts
해당 errorCode if문을 가지고 조건부 처리해줌.
이후 전체적인  errorCode에 따른 처리 정형화 과정 있으면 좋을듯
=> [#215]  이미 가입되어 있는 사용자가 회원가입 시도 플로우 추가

server/src/docs/asciidoc/index.adoc, server/src/main/java/com/example/tyfserver/auth/config/AuthenticationPrincipalConfig.java, server/src/main/java/com/example/tyfserver/auth/service/Oauth2Service.java, server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/member/domain/Account.java, server/src/main/java/com/example/tyfserver/member/domain/AccountStatus.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/dto/AccountInfoResponse.java, server/src/main/java/com/example/tyfserver/member/dto/AccountRegisterRequest.java, server/src/main/java/com/example/tyfserver/member/dto/SignUpRequest.java, server/src/main/java/com/example/tyfserver/member/exception/AccountAlreadyRegisteredException.java, server/src/main/java/com/example/tyfserver/member/exception/AccountRegisteredException.java, server/src/main/java/com/example/tyfserver/member/exception/AccountRequestingException.java, server/src/main/java/com/example/tyfserver/member/repository/AccountRepository.java, server/src/main/java/com/example/tyfserver/member/service/MemberService.java, server/src/test/java/com/example/tyfserver/member/MemberAcceptanceTest.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java, server/src/test/java/com/example/tyfserver/member/domain/MemberTest.java, server/src/test/java/com/example/tyfserver/member/service/MemberServiceTest.java
정산 가능 계정 전환을 위해 Account라는 도메인을 하나 추가했습니다.
ps. 저도 이전 테스트 3개 깨지는거는 못고쳤어요..
=> [#246]정산 가능 계정 전환을 요청 한다.

client/src/service/hooks/useDonation.ts
배포 모드에 따라 프로덕션/디벨롭 아임포트 아이디가 변경되도록 수정
=> 프로덕션 모드용 아임포트아이디 추가

server/build.gradle, server/src/main/java/com/example/tyfserver/common/config/EmbeddedRedisConfig.java, server/src/main/java/com/example/tyfserver/common/config/RedisRepositoryConfig.java, server/src/main/resources/application-test.yml, server/src/main/resources/application.yml, server/src/main/resources/static/docs/index.html, server/src/test/java/com/example/tyfserver/auth/repository/VerificationCodeRepositoryTest.java
- 테스트에서 내장 레디스를 사용하도록 Redis 설정 추가
처음에는 젠킨스의 컨테이너에서 다른 컨테이너의 레디스를 통해서 테스트를 하게 만들려고 했는데 잘 안되더라고. 
컨테이너 네트워크를 같은 걸로 해줬는데 젠킨스에서 레디스 연결이 안된다는 에러가 떴어.
아마 젠킨스 자체에서 도커를 또 만들어서 거기서 빌드를 하는 방식이라 서로 잘 연결이 안된 것 같아.
그래서 h2처럼 내장 레디스를 쓰는 방법으로 시도했어. 찾아보니까 조졸두님이 잘 정리한 글이 있더라고. (https://jojoldu.tistory.com/297)
=> [#267] Jenkins에서 Redis 관련 통합테스트가 실패하는 이슈를 해결한다

client/src/components/Refund/ApplyForm/RefundApplyForm.tsx, client/src/components/Refund/CertificationForm/RefundCertificationForm.tsx, client/src/components/Refund/RefundInfo/RefundInfo.tsx, client/src/constants/error.ts, client/src/pages/Refund/Confirm/RefundConfirmPage.tsx, client/src/service/hooks/refund/useRefund.ts, client/src/service/hooks/refund/useRefundOrderDetail.ts, client/src/service/refund/useRefund.ts, client/src/service/request/refund.ts, client/src/service/state/refund.ts, email-receipt/README.md, email-receipt/index.html
- div, html5태그 제거 후 table태그로 작성
- 스타일태그 인라인스타일로 작성
=> 결제완료 이메일 템플릿

client/main/src/constants/error.ts, client/main/src/service/refund/useRefund.ts
- 이미 인증번호 인증 횟수를 소진한 주문번호인 경우
- 이미 환불된 주문번호인 경우
- 재전송시간 이전의 주문번호인 경우
=> 환불시 주문번호 인증오류 에러케이스 세분화

client/main/src/components/Main/CreatorCard/CreatorCard.styles.ts, client/main/src/constants/error.ts, client/main/src/service/refund/useRefund.ts
nickname 요소
- width를 부모요소너비의 100%로 강제
- 좌우 padding 부여
=> 메인페이지 창작자 리스트의 카드UI 닉네임 말줄임표 정상화

client/main/src/components/Main/CreatorCard/CreatorCard.styles.ts, client/main/src/components/NavBar/NavBar.styles.ts, client/main/src/constants/error.ts, client/main/src/pages/Main/Main.styles.ts, client/main/src/pages/Main/MainPage.tsx, client/main/src/service/refund/useRefund.ts
- 네비바 닉네임영역 최대너비 지정 및 말줄임표 표시
- 메인페이지 스크롤 가능 알람 아이콘 삽입
=> hotfix: 디자인개선 v 1.2.13

client/main/src/components/@molecule/OutlineButton/OutlineButton.styles.ts, client/main/src/components/Settlement/Register/SettlementRegisterForm.styles.ts, client/main/src/pages/Donation/Payment/DonationPaymentPage.styles.ts, client/main/src/pages/Donation/Payment/DonationPaymentPage.tsx, client/main/src/service/donation/useDonation.ts
- donation 함수 pg 인자로 받아 카카오페이와 분리
- 결제수단에 '일반결제' 버튼UI 추가
=> 토스페이먼츠 결제수단 추가

server/src/main/java/com/example/tyfserver/donation/service/DonationService.java, server/src/main/resources/application-dev.yml, server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
- 포인트 차감 로직 추가
- create donation 테스트 보강
=> [#343]후원 후에 포인트가 차감이 되어야 한다. 

server/src/main/java/com/example/tyfserver/payment/dto/RefundInfoResponse.java, server/src/main/java/com/example/tyfserver/payment/service/PaymentService.java, server/src/main/java/com/example/tyfserver/payment/util/TaxIncludedCalculator.java, server/src/test/java/com/example/tyfserver/AcceptanceTest.java, server/src/test/java/com/example/tyfserver/payment/PaymentAcceptanceTest.java, server/src/test/java/com/example/tyfserver/payment/controller/PaymentControllerTest.java
=> [#346] 결제 시 부가가치세 부과하기

client/main/src/service/auth/useLoginEffect.ts, client/main/src/service/auth/useRegisterOauthEffect.ts, client/main/src/service/auth/useRegisterPageName.ts
비회원이 로그인 시도시 경고창과 함께 바로 회원가입 수행
회원이 회원가입 시도시 경고창과 함께 바로 로그인 수행
=> feat(client): 비회원 로그인시 회원가입, 회원 회원가입시 로그인 플로우 추가

client/main/src/assets/icons/naver.svg, client/main/src/components/Login/LoginForm.tsx, client/main/src/components/Register/AuthForm/RegisterAuthForm.tsx
비활성화만 해두려했는데, 아래처럼 보이는것보단
없애버리는게 더 깔끔한거같아서 없앴는데 어떤지 의견좀 남겨주세요.
=> feat(client): 네이버 로그인, 회원가입 버튼 제거

client/main/src/components/Settlement/Info/Desktop/DesktopSettlementInfo.tsx, client/main/src/components/Settlement/Info/Mobile/MobileSettlementInfo.tsx
=> feat(client): 정산관리 페이지, 환급일 안내 텍스트 수정

client/main/src/components/Point/ChargeModal/PointChargeModal.tsx
일단 시스템은 전부 필수로 작동하고, 전부 필수 맞음 (어제 같이 확인한내용)
이때, 전부다 `(필수)` 라고 붙이는것보다, 붙어있는거 빼는게 더 깔끔해서 아래와 같이 작업했어
=> feat(client): 포인트 충전 이용약관 전부 필수로 변경

client/main/src/components/@atom/Checkbox/Checkbox.styles.ts, client/main/src/components/Point/ChargeModal/PointChargeModal.styles.ts
특이사항으로 checkbox 컴포넌트에 flex-shrink:0 달아줘서, flex 내에서 사용되고 너비 줄어도, checkbox 안찌그러지게 설정했어
=> feat(client): 포인트 충전 모달 모바일 레이아웃 대응

client/main/src/components/Creator/Profile/Profile.styles.tsx, client/main/src/components/Main/CreatorCard/CreatorCard.styles.ts
img태그에 background-color 속성 사용!
=> fix(client): 투명한 프로필 이미지 불투명처리

client/main/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.styles.ts, client/main/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.tsx, client/main/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.styles.ts, client/main/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.tsx
=> fix(client): 자기소개 메세지 개행 적용

client/main/src/components/Refund/ApplyForm/RefundApplyForm.tsx, client/main/src/pages/Refund/Apply/RefundApplyPage.styles.ts
=> fix(client): 환불신청 페이지 텍스트 변경

client/main/src/constants/error.ts, client/main/src/service/auth/useRegister.ts, client/main/src/service/auth/useRegisterOauthEffect.ts, client/main/src/service/donation/useDonation.ts, client/main/src/service/donation/useDonationMessage.ts, client/main/src/service/payment/payment.ts, client/main/src/service/refund/useRefund.ts, client/main/src/service/settlement/useSettlement.ts, client/main/src/service/user/useSetting.ts
Co-Authored-By: hwano <jho2301@gmail.com>
=> feat(client): api 요청 에러 메세지 구체화

client/main/src/Global.styles.ts, client/main/src/components/@atom/Anchor/Anchor.styles.ts, client/main/src/components/@atom/Button/Button.styles.ts, client/main/src/components/@atom/IconButton/IconButton.styles.ts, client/main/src/components/@atom/SubTitle/SubTitle.styles.ts, client/main/src/components/@atom/Title/Title.styles.ts, client/main/src/pages/MyPoint/MyPointPage.styles.ts
1. 필요한 부분에 한해 부분적으로 적용하는 형식으로 변경
2. *::selection 컬러적용
=> feat(client): 전역 user-select: none 제거

client/main/src/constants/error.ts, client/main/src/service/auth/useRegisterNickname.ts, client/main/src/service/donation/useDonation.ts
=> feat(client): 회원가입시, 중복 닉네임일 경우 안내 문구 추가

client/main/server/app.js
max-age 1년, 
public
[참고문서 MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)
=> feat(client): client server,  cache-control 응답헤더 설정

client/main/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.tsx, client/main/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.tsx, client/main/src/service/settlement/useSettlement.ts
마이페이지, 내 페이지 공유하기 => 후원링크 공유하기
정산신청페이지, 계좌정보 등록에 성공했습니다! => 계좌정보 등록에 전송되었습니다. 검토에는 2~3일정도 소요됩니다.
=>  feat(client): 어플리케이션 내 텍스트 변경

client/main/src/components/Main/CreatorList/Desktop/DesktopCreatorList.styles.ts, client/main/src/components/Point/ChargeModal/PointChargeModal.tsx, client/main/src/components/Spinner/Spinner.styles.ts, client/main/src/constants/device.ts, client/main/src/service/payment/payment.ts
=> feat(client): 메인페이지 창작자리스트, 데스크탑 해상도에서 카드 4개로 확장

client/main/src/components/Creator/CreatorInfo/CreatorInfo.tsx, client/main/src/components/Creator/CreatorInfo/Desktop/DesktopCreatorInfo.tsx, client/main/src/components/Creator/CreatorInfo/Mobile/MobileCreatorInfo.tsx, client/main/src/components/Donation/AmountForm/DonationAmountForm.tsx, client/main/src/constants/popup.ts, client/main/src/mock/mockData.ts, client/main/src/pages/Creator/CreatorPage.tsx, client/main/src/types.ts
* feat: 정산 인증 받지 못한 계정, 도네이션하기 버튼 disable 처리
* feat: 도네이션 팝업창 사이즈 재조정
=> release v2.0.1

client/main/src/pages/Register/Success/RegisterSuccessPage.styles.ts, client/main/src/pages/Register/Success/RegisterSuccessPage.tsx
=> feat(client): 회원가입 완료페이지, 계좌신청페이지 링크 버튼 추가

client/main/src/service/@request/donation.ts, client/main/src/service/donation/useDonationMessage.ts
useDonationMessage에 useAccessToken사용해서  token값 받아오고
requestSendDonationMessage에 전달하도록 함수 인자 변경하고 전달했어
=> fix: 도네이션 메시지 등록 요청에 Authorization 헤더 추가

client/main/src/pages/Main/MainPage.tsx, client/main/src/utils/throttle.ts, client/main/src/utils/useScroll.ts
- useScroll 커스텀 훅 구현 및 downicon 조건부 렌더링 구현
=> feat(client): 스크롤 다 내리면 downicon 안보이게끔 처리

server/build.gradle
close #544 
이거를 하면 의존성 트리를 확인 가능. 문제가 있는 log4j 버전 사용하는 것을 확인
gradle에서 버전 업데이트 후 다시 확인했더니 버전 업데이트 완료된 것을 확인!
=> hotfix(server): log4j bug fixed
