woowacourse-teams/2021-tyf

server/src/main/java/com/example/tyfserver/common/dto/ErrorResponse.java, server/src/main/java/com/example/tyfserver/donation/controller/DonationController.java, server/src/main/java/com/example/tyfserver/donation/domain/Donation.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationMessageRequest.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationRequest.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationResponse.java, server/src/main/java/com/example/tyfserver/donation/repository/DonationRepository.java, server/src/main/java/com/example/tyfserver/donation/service/DonationService.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/domain/Point.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepository.java, server/src/main/resources/application.yml, server/src/test/java/com/example/tyfserver/donation/repository/DonationRepositoryTest.java, server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
후원 요청 시 멤버를 찾고, 해당 멤버의 포인트를 올려준 뒤 후원 데이터를 DB에 저장. 후원 응답은 DB에 저장된 후원의 ID값을 전달.
클라이언트에서 해당 후원 ID와 함께 후원자 이름과 메시지를 담아 후원 메시지 전송 API로 요청.  
Point 객체 추가하고, 후원 시에 해당 Long point 값 변경이 이루어짐
```json
{
"creator_id": 1,
"donation_amount" : 1000
}
```
```json
RESPONSE / success
201 CREATED
{
"donation_id": 1,
}
```
```json
RESPONSE / error
400 BAD REQUEST
{
"message": "error_donation_request"
}
```
```json
REQUEST
{
"name": "userName",
"message": "당신을 응원합니다."
}
```
```json
RESPONSE
201 CREATED
{}
```
```json
RESPONSE
400 BAD REQUEST
{
"message": "error_donation_message_send"
}
```
=> [#7] 후원 요청 및 메시지 전송 API 구현

server/src/main/java/com/example/tyfserver/auth/config/AuthenticationPrincipalConfig.java, server/src/main/java/com/example/tyfserver/auth/config/Oauth2Config.java, server/src/main/java/com/example/tyfserver/auth/controller/Oauth2Controller.java, server/src/main/java/com/example/tyfserver/auth/domain/Oauth2.java, server/src/main/java/com/example/tyfserver/auth/dto/SignUpResponse.java, server/src/main/java/com/example/tyfserver/auth/exception/SignUpRequestException.java, server/src/main/java/com/example/tyfserver/auth/service/Oauth2Service.java, server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/member/dto/MemberDetailResponse.java, server/src/main/java/com/example/tyfserver/member/dto/MemberPrivateResponse.java, server/src/main/java/com/example/tyfserver/member/dto/SignUpReadyResponse.java, server/src/main/java/com/example/tyfserver/member/service/MemberService.java, server/src/test/java/com/example/tyfserver/member/MemberAcceptanceTest.java
close #77
1. 이미 `MemberResponse`가 있어서 자신만 볼수있는 비공개 정보는 `MemberPrivateResponse`라고 이름지었는데 다른 좋은 의견있으면 많이 내주세요!ㅎㅎ
2. 아직은 `MemberPrivateResponse`만 가지고 있는 비공개 정보가 딱히 없어서 `MemberResponse`와 똑같긴해요. 나중에 생길테니까 미리 분리해놨어요.
3. 기존의 `SignUpResponse`를 `SignUpReadyResponse`로 변경하고 token과 pageName을 담는 `SignUpResponse`를 새로 만들었어요.
=> [#77] 창작자가 자신의 정보를 조회하는 API를 작성한다.

server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/member/dto/CurationsResponse.java, server/src/main/java/com/example/tyfserver/member/repository/MemberQueryRepository.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepository.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepositoryImpl.java, server/src/main/java/com/example/tyfserver/member/service/MemberService.java, server/src/test/java/com/example/tyfserver/member/repository/MemberRepositoryImplTest.java
방식들을 생각하느라 조금 늦었습니다!  지금까지 받은 후원금액 top5 멤버의 닉네임과 총 금액을 갖고왔습니다.  
처음에는 멤버에 대한 정보를 가지고 올 때에 도네이션을 페치 조인해서 service 내부에서 금액들을 합치고 정렬하고 상위 5명을 뽑아서 dto로 변환 후 return 해주는 방식을 생각했으나 쿼리로 처리할 수 있는 부분이기 이 방식은 버려졌습니다.  
그 후 생각한 방식은 도네이션 테이블에서 멤버로 그룹지어서 sum(amount) 해서 member_id와 sum(amount)를 갖고온 뒤에 이 member_id를 따로 멤버 테이블에 조회하는 방식이었습니다. 인라인 서브쿼리를 사용해야 된다고 생각했는데, jpa는 인라인 서브쿼리를 지원하지 않기 때문에 쿼리를 2번에 나눠 진행해야 한다고 생각했고 이 또한 service에 로직을 두지말고 repository 에서 처리해야 된다고 생각했습니다. 그러나 쿼리 2번 나가야 하는건 착각이었고 1번에 끌고 올 수 있었습니다.  
Member를 들고오는 것이 아니라 nickname과 sum(amount)에 관한 값만 들고와야 했기 때문에 Dto를 리턴하는 식으로 진행했습니다.  
가지고오는 데이터 수를 5개로 제한해야 했기도 했고 쿼리를 ``@Query`` 내에 적기 조금 길었기 때문에 따로 사용자 정의 레포지터리를 만들어서 진행했습니다.  
사용자 정의 레포지터리에 대해 간략히 설명하겠습니다.  
기존에 저희는 ``public interface MemberRepository extends JpaRepository<Member, Long>`` 의 …
=> [#84] 후원금 순 큐레이션 리스트를 보여준다.

server/src/main/java/com/example/tyfserver/auth/controller/Oauth2Controller.java, server/src/main/java/com/example/tyfserver/auth/domain/GoogleOauth2.java, server/src/main/java/com/example/tyfserver/auth/domain/KakaoOauth2.java, server/src/main/java/com/example/tyfserver/auth/domain/NaverOauth2.java, server/src/main/java/com/example/tyfserver/auth/domain/Oauth2.java, server/src/main/java/com/example/tyfserver/auth/dto/Oauth2InfoDto.java, server/src/main/java/com/example/tyfserver/auth/dto/Oauth2Request.java, server/src/main/java/com/example/tyfserver/auth/service/Oauth2Service.java, server/src/main/resources/application-oauth2-encrypted.yml, server/src/main/resources/application-oauth2.yml
login과 signup의 리다이렉트 url 서버 단에서 관리
- Oauth2Request 생성
login과 signup은 현재 컨트롤러 단에서 한번 분기가 됨.
그러나 login과 signup의 oauth2 request 메시지를 만드는 부분은 1곳임.
oauth2 request 정보에 관한 부분을 Oauth2Request (dto)로 한번 감쌈.
- 추가 리다이렉트 URL 암호화
=> [#83]로그인/회원 가입 리다이렉트 URL을 분리

server/src/main/java/com/example/tyfserver/banner/service/BannerService.java, server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/member/dto/TokenValidationRequest.java, server/src/test/java/com/example/tyfserver/member/MemberAcceptanceTest.java
Close #95
토큰 검증로직을 가진 `AuthenticationService`를 어디서 참조해야 할지 고민했습니다.
1. `MemberController`에서 참조
2. `MemberService`에서 참조
3. `AuthenticationInterceptor` 인터셉터에 path를 추가하여 구현
1번 채택: 컨트롤러에서 참조하도록 했습니다.
2번 탈락: 파즈와도 얘기했지만 서비스에서 서비스를 참조하는건 순환참조가 일어날 가능성이 생기고, 계층이 불명확해집니다.
3번 탈락: 인터셉터에서 처리하면 핵심로직인 토큰검증을 해당 컨트롤러 메서드에서 알수없기 때문에 가독성과 유지보수성이 매우 떨어집니다.
---
앗 실수...브랜치를 feature로 안했네유;;
=> [#95] 토큰 유효성검사 API 작성

client/src/App.tsx, client/src/components/Creator/Profile/Profile.styles.tsx, client/src/components/Creator/Profile/Profile.tsx, client/src/components/Main/CreatorCard/CreatorCard.tsx, client/src/components/Menu/Menu.tsx, client/src/mock/mockData.ts, client/src/pages/Donation/Donation/DonationPage.tsx, client/src/pages/Donation/Success/DonationSuccessPage.tsx, client/src/pages/Statistics/StatisticsPage.tsx, client/src/service/hooks/useCreator.ts, client/src/service/request/creator.ts, client/src/service/state/creator.ts, client/src/types.ts
1. Creator타입 사용해야돼 (Register라는 타입이 필요없으.)
2. API호출함수, 리코일 셀렉터패밀리 만들고
3. API문서 확정안났을때 작성한 스키마 다 고쳐놨으
4. 서버에서 pageName으로 주더라도 클라이언트는 creatorId로 써야할듯 추후에 변경될수있으니까
=> 창작자  프로필 컴포넌트 구현

client/src/components/Creator/DonationList/DonationList.tsx, client/src/service/hooks/useCreatorDonations.ts
- 리코일 selector 사용으로 suspense에서 대신 렌더해주는것때문에 스크롤이 위로 올라간것
- 리코일 사용 로직 제거 후 직접 api 콜
=> 후원메세지 더보기시 스크롤이 위로올라가는현상

server/src/docs/asciidoc/index.adoc, server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/payment/controller/PaymentController.java, server/src/main/java/com/example/tyfserver/payment/domain/Payment.java, server/src/main/java/com/example/tyfserver/payment/domain/PaymentInfo.java, server/src/main/java/com/example/tyfserver/payment/dto/PaymentSaveRequest.java, server/src/main/java/com/example/tyfserver/payment/exception/IllegalPaymentInfoException.java, server/src/main/java/com/example/tyfserver/payment/exception/PaymentRequestException.java, server/src/main/java/com/example/tyfserver/payment/exception/PaymentSaveRequestException.java, server/src/main/java/com/example/tyfserver/payment/service/PaymentService.java, server/src/main/java/com/example/tyfserver/payment/util/IamPortPaymentServiceConnector.java, server/src/test/java/com/example/tyfserver/banner/controller/BannerControllerTest.java, server/src/test/java/com/example/tyfserver/donation/controller/DonationControllerTest.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java, server/src/test/java/com/example/tyfserver/payment/controller/PaymentControllerTest.java, server/src/test/java/com/example/tyfserver/payment/domain/PaymentTest.java, server/src/test/java/com/example/tyfserver/payment/service/PaymentServiceTest.java
- Payment에 대한 서비스, 컨트롤러 슬라이싱 테스트 추가
- Payment 추가된 API RestDocs 작성
- 변경된 도네이션 로직에 따른 예외 사항 추가
- 실 결제정보가 PAID가 아닐경우
- 실 결제정보와 저장된 결제정보 Id 미일치
- 실 결제정보와 저장된 결제정보 amount 미일치
- 실 결제정보와 저장된 결제정보 pageName 미일치
=> [#189]Payment 서비스, 컨트롤러 슬라이싱 테스트

client/src/constants/error.ts, client/src/service/hooks/useDonationMessageList.ts
자신의 후원목록을 불러오는 과정에서 '유효하지 않은 토큰' 에러 발생시
로그인이 만료되었습니다. 메세지와 함께 새로고침
=> [#223] 회원 자신의 후원메세지 유효하지 않은 토큰시 처리 플로우

client/src/App.tsx, client/src/components/@molecule/Carousel/Carousel.styles.ts, client/src/components/@molecule/Carousel/Carousel.tsx, client/src/components/Main/CreatorList/Desktop/DesktopCreatorList.styles.ts, client/src/components/Menu/Desktop/DesktopMenu.tsx, client/src/components/Menu/Mobile/MobileMenu.tsx, client/src/components/Settlement/Info/Desktop/DesktopSettlementInfo styles.ts, client/src/components/Settlement/Info/Desktop/DesktopSettlementInfo.stories.tsx, client/src/components/Settlement/Info/Desktop/DesktopSettlementInfo.tsx, client/src/components/Settlement/Info/Mobile/MobileSettlementInfo styles.ts, client/src/components/Settlement/Info/Mobile/MobileSettlementInfo.stories.tsx, client/src/components/Settlement/Info/Mobile/MobileSettlementInfo.tsx, client/src/components/Settlement/Info/SettlementInfo.tsx, client/src/constants/style.ts, client/src/pages/Settlement/SettlementPage.stories.tsx, client/src/pages/Settlement/SettlementPage.styles.ts, client/src/pages/Settlement/SettlementPage.tsx, client/src/service/hooks/creator/useCreatorList.ts, client/src/service/hooks/donation/useDonation.ts, client/src/service/hooks/user/useSettlement.ts, client/src/service/hooks/user/useStatistics.ts, client/src/service/request/refund.ts, client/src/service/state/settlement.ts, client/src/utils/useWindowResize.ts
- api 요청함수 만들어서 교체하면 기능 완성! (api 스키마 미완성)
- Carousel 컴포넌트 따로 분리해서 구현 (메인페이지의 창작자 리스트도 추후 교체예정)
- windowResize 전역상태로 변경(useWindowResize 훅을 호출하는 컴포넌트가 늘어갈 때마다 이벤트리스너가 추가되는 현상 해결)
=> [#259] 정산 관리 페이지 마크업 및 기능 구현 

server/src/docs/asciidoc/index.adoc, server/src/main/java/com/example/tyfserver/DataLoader.java, server/src/main/java/com/example/tyfserver/admin/controller/AdminController.java, server/src/main/java/com/example/tyfserver/admin/dto/AccountCancelRequest.java, server/src/main/java/com/example/tyfserver/admin/dto/AccountRejectRequest.java, server/src/main/java/com/example/tyfserver/admin/dto/RequestingAccountResponse.java, server/src/main/java/com/example/tyfserver/admin/service/AdminService.java, server/src/main/java/com/example/tyfserver/common/util/S3Connector.java, server/src/main/java/com/example/tyfserver/common/util/SmtpMailConnector.java, server/src/main/java/com/example/tyfserver/member/controller/MemberController.java, server/src/main/java/com/example/tyfserver/member/domain/Account.java, server/src/main/java/com/example/tyfserver/member/domain/AccountStatus.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/dto/AccountInfoResponse.java, server/src/main/java/com/example/tyfserver/member/dto/AccountRegisterRequest.java, server/src/main/java/com/example/tyfserver/member/exception/AccountRegisterValidationRequestException.java, server/src/main/java/com/example/tyfserver/member/repository/MemberQueryRepository.java, server/src/main/java/com/example/tyfserver/member/repository/MemberRepositoryImpl.java, server/src/main/java/com/example/tyfserver/member/service/MemberService.java, server/src/test/java/com/example/tyfserver/AcceptanceTest.java, server/src/test/java/com/example/tyfserver/admin/AdminAcceptanceTest.java, server/src/test/java/com/example/tyfserver/admin/controller/AdminControllerTest.java, server/src/test/java/com/example/tyfserver/admin/service/AdminServiceTest.java, server/src/test/java/com/example/tyfserver/member/MemberAcceptanceTest.java, server/src/test/java/com/example/tyfserver/member/controller/MemberControllerTest.java, server/src/test/java/com/example/tyfserver/member/domain/MemberTest.java, server/src/test/java/com/example/tyfserver/member/repository/MemberRepositoryImplTest.java, server/src/test/java/com/example/tyfserver/member/service/MemberServiceTest.java
- 계좌 등록 신청 승인 API
- 계좌 등록 신청 반려 API
- 등록 요청 계좌 조회 API
- 계좌 등록 요청 유효성 검증
- 해당 API에 대한 도메인, 레포, 서비스, 컨트롤러, 인수 테스트 작성
아직 백오피스 로그인이 들어가 있지 않아 인수테스트에서 토큰인증은 하지 못했습니다.
어드민 인증을 뺀 기능 수행 에 대한 인수테스트만 현재 진행했습니다. 
계좌 등록 신청과 같은 경우 통장사본, 계좌번호, 계좌주(?), 은행을  "multipart/form-data" content type으로
묶어서 보내는데, 테스트에서는 한글이 깨집니다.
RestAssured에서  "multipart/form-data"  리퀘스트를 utf-8로 인코딩하는 방법을 찾아봤지만 결국 못찾았어요 ㅜ
다만 포스트맨으로 테스트 결과 한글이 잘 찍힙니다!!
```
2021-08-11 01:16:56.785 http-nio-8080-exec-5 15223 [DEBUG] [o.h.internal.util.EntityPrinter         ] : com.example.tyfserver.member.domain.Account
{createdAt=2021-08-11T01:16:29.416986, 
accountHolder=한글입니다., bank=한글은, bankbookUrl=uploadedBankBookUrl, 
id=1, accountNumber=1234-1234-1234, status=REQUESTING}
2021-08-11 01:16:56.785 http-nio-8080-exec-5 15223 [DEBUG] …
```
=> [#250]백오피스에서 정산 가능 계정을 승인 및 반려 한다.

server/src/main/java/com/example/tyfserver/common/util/SmtpMailConnector.java, server/src/main/java/com/example/tyfserver/donation/controller/DonationController.java, server/src/main/java/com/example/tyfserver/donation/domain/Donation.java, server/src/main/java/com/example/tyfserver/donation/domain/DonationType.java, server/src/main/java/com/example/tyfserver/donation/domain/Message.java, server/src/main/java/com/example/tyfserver/donation/dto/DonationRequest.java, server/src/main/java/com/example/tyfserver/donation/repository/DonationRepository.java, server/src/main/java/com/example/tyfserver/donation/service/DonationService.java, server/src/main/java/com/example/tyfserver/member/domain/Member.java, server/src/main/java/com/example/tyfserver/member/domain/Point.java, server/src/main/java/com/example/tyfserver/member/dto/MemberResponse.java, server/src/main/java/com/example/tyfserver/member/exception/NotEnoughPointException.java, server/src/main/java/com/example/tyfserver/payment/controller/PaymentController.java, server/src/main/java/com/example/tyfserver/payment/domain/Item.java, server/src/main/java/com/example/tyfserver/payment/domain/Payment.java, server/src/main/java/com/example/tyfserver/payment/dto/PaymentCompleteResponse.java, server/src/main/java/com/example/tyfserver/payment/dto/RefundInfoResponse.java, server/src/main/java/com/example/tyfserver/payment/exception/ItemNotFoundException.java, server/src/main/java/com/example/tyfserver/payment/exception/PaymentCompleteRequestException.java, server/src/main/java/com/example/tyfserver/payment/exception/RefundGuaranteeDurationException.java, server/src/main/java/com/example/tyfserver/payment/repository/PaymentRepository.java, server/src/main/java/com/example/tyfserver/payment/service/PaymentService.java, server/src/main/resources/templates/mail-charge-complete.html, server/src/test/java/com/example/tyfserver/donation/service/DonationServiceTest.java
request: itemId
response : merchantUid, itemName, amount, email  
request : impUid, merchantUid  
response : point  
<br/>
request : pageName, point  
response : donationId, name, message, amount, createdAt  
request : name, message, secret  
response : -  
환불은 내부로직만 바뀌고 엔드포인트 바뀐 것 없음  
<br/>
본인이 보낸 후원을 나중에 볼 수 있게끔 하기위해서 ``Donation``에 ``DonationType`` 이라는 enum 타입 필드를 추가해주고,  
후원 요청 시에 2개의 ``Donation``을 각각 만들어서 creator와 donator가 가지고 있는 List<Donation>에 집어넣어줬을 경우,  
``/donations/{donationId}/message`` 호출 시에 하나의 ``donationId`` 만 들어올텐데 두 도네이션의 ``Message``를 다 업데이트 하기가 애매한 것 같음!  
후원자가 본인이 보낸 후원 메세지에 대한 정보가 defaultMessage 여도 상관없다면 괜찮지만... 아니면 프론트한테 ``/donations`` 이후에 response 로 donationId를 2개를 response 해주고 message API 에서 2개의 id를 모두 받는 방법도 있긴하지만!  
<br/>
1. 이제 거의 모든 API가 토큰이 필요할텐데 (다 인가??) 인수테스트 …
=> [#326] 후원 및 환불 api 리팩토링 및 구현

client/main/src/components/Donation/MessageForm/DonationMessageForm.tsx, client/main/src/components/Settlement/Info/Desktop/DesktopSettlementInfo.tsx, client/main/src/components/Settlement/Info/Mobile/MobileSettlementInfo.tsx, client/main/src/service/donation/useDonation.ts, client/main/src/service/donation/useDonationMessage.ts, client/main/src/service/donation/useDonationMessageForm.ts, client/main/src/types.ts
1. 관련 로직 제거
2. 메세지 POST 요청의 닉네임 값은 POST donation으로 받아온 닉네임을 다시 보내도록 설정
- 추후에 API를 변경하면 같이 변경하면 좋을듯!
=> feat(client): 도네이션 메세지폼, 닉네임 고정 처리

client/main/src/service/auth/useRegisterNickname.ts
=> feat(client): 닉네임 일본어, 중국어 안되게 변경

client/main/src/components/Settlement/Register/SettlementRegisterForm.styles.ts, client/main/src/components/Settlement/Register/SettlementRegisterForm.tsx, client/main/src/pages/Settlement/SettlementPage.tsx
transition 지운 이유는 transition때문에 은행선택 모바일 화면의 fixed가 깨져서 지움
=> feat(client): 계좌등록 페이지 모바일 대응

client/main/src/service/creator/useDonationMessageList.ts
1. 커스텀훅에서 didMount 이펙트훅에서 리스트 초기화
2. 내 후원리스트 불러오는 함수의 state, setState 콜백함수 적용
=> fix(client): 타 창작자페이지에서 내 페이지로 이동시, 후원메시지리스트 갱신이 안되는 현상

server/src/main/java/com/example/tyfserver/DatabaseCleanup.java, server/src/test/java/com/example/tyfserver/AcceptanceTest.java, server/src/test/java/com/example/tyfserver/DatabaseCleanup.java
DirtiesContext로 테스트 격리 하는 대신
인수테스트 시작 시 EntityManager를 사용하여 테이블을 TRUNCATE하는 식으로 변경했습니다.
적용 전 테스트 수행 시간은 1분 
적용 후 테스트 수행 시간은 11초로
현저히 줄어든것을 확인할 수 있었습니다.
https://devlopsquare.tistory.com/227
관련 내용 블로그에 정리해봤습니다!
=> refactor(server): 테스트 시간을 단축한다 (DirtiesContext 사용하지 않도록)

client/main/src/service/auth/useRegisterNickname.ts, client/main/src/service/auth/useRegisterPageName.ts, client/main/src/service/settlement/useSettlementAccountForm.ts, client/main/src/service/user/useSettingForm.ts
1. 설정페이지 닉네임
2. 정산계좌신청 이름
3. 정산계좌신청 계좌번호 
4. 회원가입 모든 텍스트 Input
=> feat(client): 회원가입, 설정, 정산신청페이지 setState시 trim 적용

server/src/main/java/com/example/tyfserver/admin/service/AdminService.java
- 통장사본으로 계좌 인증하던 로직 제거로 발생한 이슈
- 추후 멤버 도메인의 bankbookurl 제거 필요
=> hotfix: 계좌승인 로직에서 S3에서 통장사본 지우는 로직 제거

server/src/main/resources/application.yml
close #539 
[gzip 설정 참고 링크](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.enable-response-compression)
[히카리 풀 설정 참고 링크](https://hyunsoori.tistory.com/2)
처음에는 우리가 성능측정을 했던 것 처럼 목표 VU에 맞춰서 hikari pool-size를 조정하는게 맞지 않나? 라는 생각을 했어  
그런데, 모든 요청이 db를 타는 것도 아니고(우리의 경우 다 타지만) 모든 요청의 개수에 맞게끔 커넥션을 가지는 것도 비효율적이라는 것을 깨달았어. 핵심적으로는 히카리풀의 공식 문서에 나와있는 이 설명 때문에 기본설정인 10개의 size를 변경하지 않게 됐어  
결론: 히카리풀 사이즈를 변경하려 했으나 변경안했다. cache 전략도 적용하려다 적용안했다. 그냥 hikari cp의 name과 size 명시만 해주었다.
그리고 추가적으로 이 링크들을 읽으면 좋을 것 같아! 좀 많이 도움되는 것 같아.
https://jeong-pro.tistory.com/204  
https://jaehun2841.github.io/2020/01/27/2020-01-27-hikaricp-maximum-pool-size-tuning/#generatedvaluestrategy-generationtypeauto  
https://hyuntaeknote.tistory.com/12 …
=> feat(server): 히카리 풀 설정 및 gzip 설정

server/src/main/java/com/thankyou_for/common/exception/ApiConnectionException.java, server/src/main/java/com/thankyou_for/common/util/ApiSender.java
close #537 
외부 API 호출 시에 우리가 우려하던 사항들을 코드 리팩토링 했어.  
1. connection/read time out 설정
2. connection pool 설정
3. Exception 처리
Exception을 생성하면서 common-001로 만드려고 했는데 기존에 001~003이 있더라고? 노션 에러페이지 목록에는 없었는데 말이야.  
그래서 common-004로 생성하면서 노션에 추가해놨어  
이번에 리팩토링한 내용들 변경하면서 학습 내용들을 공유하려고 PR 커멘트 작성하다가 내용이 좀 방대하길레 TIL로 작성했어  
읽어보면 도움 될거야 아마.. (?)  
timeOut 시간은 connection/read 둘 다 2초로 설정했고,  
connection pool의 개수는 내가 그냥 임의로 설정해놨는데, 이 부분에 대해서는 좋은 의견있으면 말해줘~!
<br/>
<br/>
RestTemplate을 선언할 때에 ``new RestTemplate()`` 다음과 같이 선언해서 이용할 수가 있다.  
그런데 이용법에 대한 구글링을 찾다보니 ``HttpComponentsClientHttpRequestFactory``를 생성자 파라미터로 넘겨주어 RestTemplate을 생성하는 코드를 찾아볼 수가 있었다. 다음과 같이 말이다. 밑에는 학습내용이야. 리뷰 땡큐
```java
HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
HttpClient client = …
```
=> feat(server): RestTemplate Connection Pool 설정 및 TimeOut 설정
